version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  server:
    build: server
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - MONGODB_PATH=mongodb://mongo:27017/auth
    links:
      - mongo
  client:
    build: client
    ports:
      - "8080:8080"
    links:
      - server
    depends_on:
      - server